
[font]
size = 10.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 0
y = 0

[general]
import = ["/home/zantox/.alacritty-colorscheme/themes/argonaut.toml"]

[terminal]
